# Generated by Django 2.2.2 on 2019-06-12 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('boardid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Boards')),
            ],
            options={
                'unique_together': {('boardid', 'id')},
            },
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=256)),
                ('boardid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Boards')),
                ('listid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Lists')),
            ],
        ),
    ]
