# Generated by Django 2.2.2 on 2019-06-13 13:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20190613_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='boardid',
        ),
        migrations.AddField(
            model_name='cards',
            name='duedate',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='cards',
            name='title',
            field=models.CharField(default='title', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cards',
            name='content',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='cards',
            name='listid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listcards', to='boards.Lists'),
        ),
        migrations.AlterField(
            model_name='lists',
            name='boardid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardlists', to='boards.Boards'),
        ),
    ]
